#!/bin/bash

echo "Starting K3s Server (Controller) installation..."

# Configure host passwordless SSH access using the key generated by Vagrant
if [ -f /vagrant/host_key.pub ]; then
  mkdir -p /home/vagrant/.ssh
  cat /vagrant/host_key.pub >> /home/vagrant/.ssh/authorized_keys
  chown -R vagrant:vagrant /home/vagrant/.ssh
  chmod 700 /home/vagrant/.ssh
  chmod 600 /home/vagrant/.ssh/authorized_keys
fi

# Install K3s as a server, binding it to the specific IP from the project requirements
sudo fallocate -l 3G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile


sudo apt update
sudo apt install curl -y

export INSTALL_K3S_EXEC="server --bind-address=192.168.56.110 --node-ip=192.168.56.110 --kubelet-arg=fail-swap-on=false --write-kubeconfig-mode 644"
curl -sfL https://get.k3s.io | sh -

# Make kubectl accessible for the default vagrant test without needing 'sudo'
chmod 644 /etc/rancher/k3s/k3s.yaml
echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> /home/vagrant/.bashrc
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

echo 'alias k=kubectl' >> /home/vagrant/.bashrc

echo "K3s Server installation complete."

echo "Deploying applications and ingress..."
kubectl apply -f /vagrant/confs/

echo "Setup complete! All applications and ingress deployed."
